{
 "title": "Go-Ethereum-By-Instance",
 "description": "A Prometheus metric dashboard for go-ethereum, supports all blockchains compatible with go-ethereum",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "PBFA97CFB590B2093" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_head_block{}, instance)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Chain Reorg Add",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_add{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain Reorg Drop",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_drop{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    },
    {
     "expr": "chain_snapshot_commits{instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{instance=~\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    },
    {
     "expr": "rate(txpool_known{instance=~\"$instance\"}[1m])",
     "legendFormat": "known"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{instance=~\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=~\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    },
    {
     "expr": "rate(txpool_known{instance=~\"$instance\"}[1m])",
     "legendFormat": "known"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success RPC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(gzond_rpc_requests_success_count{instance=\"$instance\"}[5m])) by (instance, method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Failure RPC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(gzond_rpc_requests_failure_count{instance=\"$instance\"}[5m])) by (instance, method)",
       "legendFormat": "{{method}}"
      },
      {}
     ]
    },
    {
     "title": "Success RPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "sum(rate(gzond_rpc_requests_success{quantile='$quantile', instance=\"$instance\"}[5m])) by (instance, method) \n/ \nsum(rate(gzond_rpc_requests_success_count{instance=\"$instance\"}[5m])) by (instance, method) /1e6 \n< 1e200",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Failure RPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 321 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "sum(rate(gzond_rpc_requests_failure{quantile='$quantile', instance=\"$instance\"}[5m])) by (instance, method) / sum(rate(gzond_rpc_requests_failure_count{instance=\"$instance\"}[5m])) by (instance, method) /1e6",
       "legendFormat": "{{method}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(system_cpu_sysload{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "system"
      },
      {
       "expr": "avg(system_cpu_syswait{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "iowait"
      },
      {
       "expr": "avg(system_cpu_procload{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "gzond"
      },
      {
       "expr": "avg(system_cpu_goroutines{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(system_cpu_threads{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(system_memory_allocs{instance=~\"$instance\"}[1m])",
       "legendFormat": "alloc"
      },
      {
       "expr": "system_memory_used{instance=~\"$instance\"}",
       "legendFormat": "used"
      },
      {
       "expr": "system_memory_held{instance=~\"$instance\"}",
       "legendFormat": "held"
      },
      {
       "expr": "rate(system_memory_frees{instance=~\"$instance\"}[1m])",
       "legendFormat": "free"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(system_disk_readbytes{instance=~\"$instance\"}[1m])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(system_disk_writebytes{instance=~\"$instance\"}[1m])",
       "legendFormat": "write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(p2p_ingress{instance=~\"$instance\"}[1m])",
       "legendFormat": "ingress-rate"
      },
      {
       "expr": "rate(p2p_egress{instance=~\"$instance\"}[1m])",
       "legendFormat": "egress-rate"
      },
      {
       "expr": "p2p_ingress{instance=~\"$instance\"}",
       "legendFormat": "igress-flow"
      },
      {
       "expr": "p2p_egress{instance=~\"$instance\"}",
       "legendFormat": "egress-flow"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "p2p_peers{instance=~\"$instance\"}",
       "legendFormat": "peers"
      },
      {
       "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
       "legendFormat": "dials"
      },
      {
       "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
       "legendFormat": "serves"
      }
     ]
    }
   ]
  },
  {
   "title": "Downloader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throttle",
     "type": "stat",
     "description": "Measured in #peers per second",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(eth_downloader_throttle{instance=~\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eth_downloader_bodies_in{instance=~\"$instance\"}[1m])",
       "legendFormat": "bodies in"
      },
      {
       "expr": "rate(eth_downloader_headers_in{instance=~\"$instance\"}[1m])",
       "legendFormat": "headers in"
      },
      {
       "expr": "rate(eth_downloader_receipts_in{instance=~\"$instance\"}[1m])",
       "legendFormat": "receipts in"
      }
     ]
    },
    {
     "title": "Abnormal QPS",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "eth_downloader_bodies_drop{instance=~\"$instance\"}",
       "legendFormat": "bodies drop"
      },
      {
       "expr": "eth_downloader_headers_drop{instance=~\"$instance\"}",
       "legendFormat": "headers drop"
      },
      {
       "expr": "eth_downloader_receipts_drop{instance=~\"$instance\"}",
       "legendFormat": "receipts drop"
      },
      {
       "expr": "eth_downloader_bodies_timeout{instance=~\"$instance\"}",
       "legendFormat": "bodies timeout"
      },
      {
       "expr": "eth_downloader_headers_timeout{instance=~\"$instance\"}",
       "legendFormat": "headers timeout"
      },
      {
       "expr": "eth_downloader_receipts_timeout{instance=~\"$instance\"}",
       "legendFormat": "receipts timeout"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(eth_downloader_bodies_req{instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
       "legendFormat": "bodies(q={{quantile}})"
      },
      {
       "expr": "rate(eth_downloader_headers_req{instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
       "legendFormat": "headers(q={{quantile}})"
      },
      {
       "expr": "rate(eth_downloader_receipts_req{instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
       "legendFormat": "receipts(q={{quantile}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waiting Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_waiting_peers{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Waiting Hashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_waiting_hashes{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Queueing Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_queueing_peers{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Queueing Hashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_queueing_hashes{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Fetching Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_fetching_peers{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Fetching Hashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "eth_fetcher_transaction_fetching_hashes{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "QPS of Transaction",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eth_fetcher_transaction_request_out{instance=~\"$instance\"}[1m])",
       "legendFormat": "request out"
      },
      {
       "expr": "rate(eth_fetcher_transaction_request_fail{instance=~\"$instance\"}[1m])",
       "legendFormat": "request fail"
      },
      {
       "expr": "rate(eth_fetcher_transaction_request_done{instance=~\"$instance\"}[1m])",
       "legendFormat": "request done"
      },
      {
       "expr": "rate(eth_fetcher_transaction_request_timeout{instance=~\"$instance\"}[1m])",
       "legendFormat": "request timeout"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_in{instance=~\"$instance\"}[1m])",
       "legendFormat": "replies in"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_known{instance=~\"$instance\"}[1m])",
       "legendFormat": "replies known"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_underpriced{instance=~\"$instance\"}[1m])",
       "legendFormat": "replies underpriced"
      },
      {
       "expr": "rate(eth_fetcher_transaction_replies_otherreject{instance=~\"$instance\"}[1m])",
       "legendFormat": "replies otherreject"
      }
     ]
    },
    {
     "title": "QPS of Block",
     "type": "timeseries",
     "description": "Measured in blocks per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(eth_fetcher_block_bodies{instance=~\"$instance\"}[1m])",
       "legendFormat": "bodies"
      },
      {
       "expr": "rate(eth_fetcher_block_headers{instance=~\"$instance\"}[1m])",
       "legendFormat": "headers"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_headers_in{instance=~\"$instance\"}[1m])",
       "legendFormat": "filter headers in"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_headers_out{instance=~\"$instance\"}[1m])",
       "legendFormat": "filter headers out"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_bodies_in{instance=~\"$instance\"}[1m])",
       "legendFormat": "filter bodies in"
      },
      {
       "expr": "rate(eth_fetcher_block_filter_bodies_out{instance=~\"$instance\"}[1m])",
       "legendFormat": "filter bodies out"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(eth_db_chaindata_disk_read{instance=~\"$instance\"}[1m])",
       "legendFormat": "ethdb read"
      },
      {
       "expr": "rate(eth_db_chaindata_disk_write{instance=~\"$instance\"}[1m])",
       "legendFormat": "ethdb write"
      },
      {
       "expr": "rate(eth_db_chaindata_ancient_read{instance=~\"$instance\"}[1m])",
       "legendFormat": "ancient read"
      },
      {
       "expr": "rate(eth_db_chaindata_ancient_write{instance=~\"$instance\"}[1m])",
       "legendFormat": "ancient write"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_input{instance=~\"$instance\"}[1m])",
       "legendFormat": "compact read"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_output{instance=~\"$instance\"}[1m])",
       "legendFormat": "compact write"
      }
     ]
    },
    {
     "title": "Session totals",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_read{instance=~\"$instance\"}",
       "legendFormat": "leveldb read"
      },
      {
       "expr": "eth_db_chaindata_disk_write{instance=~\"$instance\"}",
       "legendFormat": "leveldb write"
      },
      {
       "expr": "eth_db_chaindata_ancient_read{instance=~\"$instance\"}",
       "legendFormat": "ancient read"
      },
      {
       "expr": "eth_db_chaindata_ancient_write{instance=~\"$instance\"}",
       "legendFormat": "ancient write"
      }
     ]
    },
    {
     "title": "Storage size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_size{instance=~\"$instance\"}",
       "legendFormat": "leveldb"
      },
      {
       "expr": "eth_db_chaindata_ancient_size{instance=~\"$instance\"}",
       "legendFormat": "ancient"
      }
     ]
    },
    {
     "title": "Compact Writedelay Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_compact_writedelay_counter{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Compact",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(eth_db_chaindata_compact_time{instance=~\"$instance\"}[1m])",
       "legendFormat": "time"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_nonlevel0{instance=~\"$instance\"}[1m])",
       "legendFormat": "level0"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_level0{instance=~\"$instance\"}[1m])",
       "legendFormat": "~level0"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_memory{instance=~\"$instance\"}[1m])",
       "legendFormat": "mem"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_seek{instance=~\"$instance\"}[1m])",
       "legendFormat": "seek"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_writedelay_duration{instance=~\"$instance\"}[1m])",
       "legendFormat": "delay time"
      },
      {
       "expr": "rate(eth_db_chaindata_compact_writedelay_counter{instance=~\"$instance\"}[1m])",
       "legendFormat": "delay count"
      }
     ]
    },
    {
     "title": "Compact Writedelay Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "eth_db_chaindata_compact_writedelay_duration{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clean cache-BPS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_clean_read{instance=~\"$instance\"}[1m])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(trie_memcache_clean_write{instance=~\"$instance\"}[1m])",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Dirty cache-BPS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_gc_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(trie_memcache_flush_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "overflow"
      },
      {
       "expr": "rate(trie_memcache_commit_size{instance=~\"$instance\"}[1m])",
       "legendFormat": "commit"
      }
     ]
    },
    {
     "title": "Clean cache-Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_clean_hit{instance=~\"$instance\"}[1m])",
       "legendFormat": "hit"
      },
      {
       "expr": "rate(trie_memcache_clean_miss{instance=~\"$instance\"}[1m])",
       "legendFormat": "miss"
      },
      {
       "expr": "rate(trie_memcache_clean_hit{instance=~\"$instance\"}[1m])/(rate(trie_memcache_clean_miss{instance=~\"$instance\"}[1m])+rate(trie_memcache_clean_hit{instance=~\"$instance\"}[1m]))",
       "legendFormat": "hit rate"
      }
     ]
    },
    {
     "title": "Dirty cache-Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_dirty_hit{instance=~\"$instance\"}[1m])",
       "legendFormat": "hit"
      },
      {
       "expr": "rate(trie_memcache_dirty_miss{instance=~\"$instance\"}[1m])",
       "legendFormat": "miss"
      },
      {
       "expr": "rate(trie_memcache_dirty_hit{instance=~\"$instance\"}[1m])/(rate(trie_memcache_dirty_miss{instance=~\"$instance\"}[1m])+rate(trie_memcache_dirty_hit{instance=~\"$instance\"}[1m]))",
       "legendFormat": "hit rate"
      }
     ]
    },
    {
     "title": "MPT-Nodes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_gc_nodes{instance=~\"$instance\"}[1m])",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(trie_memcache_commit_nodes{instance=~\"$instance\"}[1m])",
       "legendFormat": "commit"
      },
      {
       "expr": "rate(trie_memcache_flush_nodes{instance=~\"$instance\"}[1m])",
       "legendFormat": "overflow"
      }
     ]
    },
    {
     "title": "MPT-Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(trie_memcache_gc_time{instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(trie_memcache_commit_time{instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
       "legendFormat": "commit"
      },
      {
       "expr": "rate(trie_memcache_flush_time{instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
       "legendFormat": "overflow"
      }
     ]
    }
   ]
  }
 ]
}